---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: Helm
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        app.kubernetes.io/managed-by: Helm
        environment: {{ .Values.environment }}
    spec:
      containers:
      - env:
        - name: MYSQL_DB_HOST
          value: "{{ .Values.mysql.url }}"
        - name: MYSQL_DB_USER
          value: "{{ .Values.mysql.user }}"
        - name: MYSQL_DB_PASS
          value: "{{ .Values.mysql.password }}"
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.app.name }}
        ports:
          - containerPort: {{ .Values.app.port }}
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
      restartPolicy: Always
