apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.app.name }}
spec:
  ports:
  - name: {{ .Values.app.name }}
    nodePort: 31096
    port: 80
    protocol: TCP
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}
  type: NodePort